"""add conversation_prompts table

Revision ID: 06c41bd3aa25
Revises: 366bf2e0758b
Create Date: 2026-06-25 13:08:06.502209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c41bd3aa25'
down_revision: Union[str, None] = '366bf2e0758b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_prompts',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_prompts_conversation_id'), 'conversation_prompts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_prompts_id'), 'conversation_prompts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_prompts_id'), table_name='conversation_prompts')
    op.drop_index(op.f('ix_conversation_prompts_conversation_id'), table_name='conversation_prompts')
    op.drop_table('conversation_prompts')
    # ### end Alembic commands ###
