"""add conversation_id to forms

Revision ID: 9f026ce4c210
Revises: 06c41bd3aa25
Create Date: 2026-06-25 13:29:15.048694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f026ce4c210'
down_revision: Union[str, None] = '06c41bd3aa25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('conversation_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'conversation_id')
    # ### end Alembic commands ###
